// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE-go file.

// Code generated by internal/gen; DO NOT EDIT.

package bigmath

import (
	"fmt"
	"math"
	"math/big"
)

// Package-level type aliases for commonly-used big types.
type (
	Accuracy = big.Accuracy
	RoundingMode = big.RoundingMode
	Word = big.Word
)

// Constants describing the Accuracy of a Float.
const (
	Below Accuracy = -1
	Exact Accuracy = 0
	Above Accuracy = +1
)

// These constants define supported rounding modes.
const (
	ToNearestEven RoundingMode = iota // == IEEE 754-2008 roundTiesToEven
	ToNearestAway                     // == IEEE 754-2008 roundTiesToAway
	ToZero                            // == IEEE 754-2008 roundTowardZero
	AwayFromZero                      // no IEEE 754-2008 equivalent
	ToNegativeInf                     // == IEEE 754-2008 roundTowardNegative
	ToPositiveInf                     // == IEEE 754-2008 roundTowardPositive
)

// Exponent and precision limits.
const (
	MaxExp  = big.MaxExp  // largest supported exponent
	MinExp  = big.MinExp  // smallest supported exponent
	MaxPrec = big.MaxPrec // largest (theoretically) supported precision; likely memory-limited
)

// Abs sets z to the (possibly rounded) value |x| (the absolute value of x)
// and returns z.
//
func (z *Float) Abs(x *Float) *Float {
	return (*Float)((*big.Float)(z).Abs((*big.Float)(x)))
}

// Acc returns the accuracy of x produced by the most recent
// operation, unless explicitly documented otherwise by that
// operation.
//
func (x *Float) Acc() Accuracy {
	return (*big.Float)(x).Acc()
}

// Add sets z to the rounded sum x+y and returns z. If z's precision is 0,
// it is changed to the larger of x's or y's precision before the operation.
// Rounding is performed according to z's precision and rounding mode; and
// z's accuracy reports the result error relative to the exact (not rounded)
// result. Add panics with [ErrNaN] if x and y are infinities with opposite
// signs. The value of z is undefined in that case.
//
func (z *Float) Add(x *Float, y *Float) *Float {
	return (*Float)((*big.Float)(z).Add((*big.Float)(x), (*big.Float)(y)))
}

// Cmp compares x and y and returns:
//   - -1 if x < y;
//   - 0 if x == y (incl. -0 == 0, -Inf == -Inf, and +Inf == +Inf);
//   - +1 if x > y.
//
func (x *Float) Cmp(y *Float) int {
	return (*big.Float)(x).Cmp((*big.Float)(y))
}

// Copy sets z to x, with the same precision, rounding mode, and accuracy as x.
// Copy returns z. If x and z are identical, Copy is a no-op.
//
func (z *Float) Copy(x *Float) *Float {
	return (*Float)((*big.Float)(z).Copy((*big.Float)(x)))
}

// Float32 returns the float32 value nearest to x. If x is too small to be
// represented by a float32 (|x| < [math.SmallestNonzeroFloat32]), the result
// is (0, [Below]) or (-0, [Above]), respectively, depending on the sign of x.
// If x is too large to be represented by a float32 (|x| > [math.MaxFloat32]),
// the result is (+Inf, [Above]) or (-Inf, [Below]), depending on the sign of x.
//
func (x *Float) Float32() (float32, Accuracy) {
	v0, v1 := (*big.Float)(x).Float32()
	return v0, v1
}

// Float64 returns the float64 value nearest to x. If x is too small to be
// represented by a float64 (|x| < [math.SmallestNonzeroFloat64]), the result
// is (0, [Below]) or (-0, [Above]), respectively, depending on the sign of x.
// If x is too large to be represented by a float64 (|x| > [math.MaxFloat64]),
// the result is (+Inf, [Above]) or (-Inf, [Below]), depending on the sign of x.
//
func (x *Float) Float64() (float64, Accuracy) {
	v0, v1 := (*big.Float)(x).Float64()
	return v0, v1
}

// GobDecode implements the [encoding/gob.GobDecoder] interface.
// The result is rounded per the precision and rounding mode of
// z unless z's precision is 0, in which case z is set exactly
// to the decoded value.
//
func (z *Float) GobDecode(buf []byte) error {
	return (*big.Float)(z).GobDecode(buf)
}

// GobEncode implements the [encoding/gob.GobEncoder] interface.
// The [Float] value and all its attributes (precision,
// rounding mode, accuracy) are marshaled.
//
func (x *Float) GobEncode() ([]byte, error) {
	v0, v1 := (*big.Float)(x).GobEncode()
	return v0, v1
}

// Int returns the result of truncating x towards zero;
// or nil if x is an infinity.
// The result is [Exact] if x.IsInt(); otherwise it is [Below]
// for x > 0, and [Above] for x < 0.
// If a non-nil *[Int] argument z is provided, [Int] stores
// the result in z instead of allocating a new [Int].
//
func (x *Float) Int(z *big.Int) (*big.Int, Accuracy) {
	v0, v1 := (*big.Float)(x).Int(z)
	return v0, v1
}

// Int64 returns the integer resulting from truncating x towards zero.
// If [math.MinInt64] <= x <= [math.MaxInt64], the result is [Exact] if x is
// an integer, and [Above] (x < 0) or [Below] (x > 0) otherwise.
// The result is ([math.MinInt64], [Above]) for x < [math.MinInt64],
// and ([math.MaxInt64], [Below]) for x > [math.MaxInt64].
//
func (x *Float) Int64() (int64, Accuracy) {
	v0, v1 := (*big.Float)(x).Int64()
	return v0, v1
}

// IsInf reports whether x is +Inf or -Inf.
//
func (x *Float) IsInf() bool {
	return (*big.Float)(x).IsInf()
}

// IsInt reports whether x is an integer.
// ±Inf values are not integers.
//
func (x *Float) IsInt() bool {
	return (*big.Float)(x).IsInt()
}

// MantExp breaks x into its mantissa and exponent components
// and returns the exponent. If a non-nil mant argument is
// provided its value is set to the mantissa of x, with the
// same precision and rounding mode as x. The components
// satisfy x == mant × 2**exp, with 0.5 <= |mant| < 1.0.
// Calling MantExp with a nil argument is an efficient way to
// get the exponent of the receiver.
//
// Special cases are:
//
// 	(  ±0).MantExp(mant) = 0, with mant set to   ±0
// 	(±Inf).MantExp(mant) = 0, with mant set to ±Inf
//
// x and mant may be the same in which case x is set to its
// mantissa value.
//
func (x *Float) MantExp(mant *Float) int {
	return (*big.Float)(x).MantExp((*big.Float)(mant))
}

// MinPrec returns the minimum precision required to represent x exactly
// (i.e., the smallest prec before x.SetPrec(prec) would start rounding x).
// The result is 0 for |x| == 0 and |x| == Inf.
//
func (x *Float) MinPrec() uint {
	return (*big.Float)(x).MinPrec()
}

// Mode returns the rounding mode of x.
//
func (x *Float) Mode() RoundingMode {
	return (*big.Float)(x).Mode()
}

// Mul sets z to the rounded product x*y and returns z.
// Precision, rounding, and accuracy reporting are as for [Float.Add].
// Mul panics with [ErrNaN] if one operand is zero and the other
// operand an infinity. The value of z is undefined in that case.
//
func (z *Float) Mul(x *Float, y *Float) *Float {
	return (*Float)((*big.Float)(z).Mul((*big.Float)(x), (*big.Float)(y)))
}

// Neg sets z to the (possibly rounded) value of x with its sign negated,
// and returns z.
//
func (z *Float) Neg(x *Float) *Float {
	return (*Float)((*big.Float)(z).Neg((*big.Float)(x)))
}

// Parse parses s which must contain a text representation of a floating-
// point number with a mantissa in the given conversion base (the exponent
// is always a decimal number), or a string representing an infinite value.
//
// For base 0, an underscore character “_” may appear between a base
// prefix and an adjacent digit, and between successive digits; such
// underscores do not change the value of the number, or the returned
// digit count. Incorrect placement of underscores is reported as an
// error if there are no other errors. If base != 0, underscores are
// not recognized and thus terminate scanning like any other character
// that is not a valid radix point or digit.
//
// It sets z to the (possibly rounded) value of the corresponding floating-
// point value, and returns z, the actual base b, and an error err, if any.
// The entire string (not just a prefix) must be consumed for success.
// If z's precision is 0, it is changed to 64 before rounding takes effect.
// The number must be of the form:
//
// 	number    = [ sign ] ( float | "inf" | "Inf" ) .
// 	sign      = "+" | "-" .
// 	float     = ( mantissa | prefix pmantissa ) [ exponent ] .
// 	prefix    = "0" [ "b" | "B" | "o" | "O" | "x" | "X" ] .
// 	mantissa  = digits "." [ digits ] | digits | "." digits .
// 	pmantissa = [ "_" ] digits "." [ digits ] | [ "_" ] digits | "." digits .
// 	exponent  = ( "e" | "E" | "p" | "P" ) [ sign ] digits .
// 	digits    = digit { [ "_" ] digit } .
// 	digit     = "0" ... "9" | "a" ... "z" | "A" ... "Z" .
//
// The base argument must be 0, 2, 8, 10, or 16. Providing an invalid base
// argument will lead to a run-time panic.
//
// For base 0, the number prefix determines the actual base: A prefix of
// “0b” or “0B” selects base 2, “0o” or “0O” selects base 8, and
// “0x” or “0X” selects base 16. Otherwise, the actual base is 10 and
// no prefix is accepted. The octal prefix "0" is not supported (a leading
// "0" is simply considered a "0").
//
// A "p" or "P" exponent indicates a base 2 (rather than base 10) exponent;
// for instance, "0x1.fffffffffffffp1023" (using base 0) represents the
// maximum float64 value. For hexadecimal mantissae, the exponent character
// must be one of 'p' or 'P', if present (an "e" or "E" exponent indicator
// cannot be distinguished from a mantissa digit).
//
// The returned *Float f is nil and the value of z is valid but not
// defined if an error is reported.
//
func (z *Float) Parse(s string, base int) (f *Float, b int, err error) {
	v0, v1, v2 := (*big.Float)(z).Parse(s, base)
	return (*Float)(v0), v1, v2
}

// Prec returns the mantissa precision of x in bits.
// The result may be 0 for |x| == 0 and |x| == Inf.
//
func (x *Float) Prec() uint {
	return (*big.Float)(x).Prec()
}

// Quo sets z to the rounded quotient x/y and returns z.
// Precision, rounding, and accuracy reporting are as for [Float.Add].
// Quo panics with [ErrNaN] if both operands are zero or infinities.
// The value of z is undefined in that case.
//
func (z *Float) Quo(x *Float, y *Float) *Float {
	return (*Float)((*big.Float)(z).Quo((*big.Float)(x), (*big.Float)(y)))
}

// Rat returns the rational number corresponding to x;
// or nil if x is an infinity.
// The result is [Exact] if x is not an Inf.
// If a non-nil *[Rat] argument z is provided, [Rat] stores
// the result in z instead of allocating a new [Rat].
//
func (x *Float) Rat(z *big.Rat) (*big.Rat, Accuracy) {
	v0, v1 := (*big.Float)(x).Rat(z)
	return v0, v1
}

// Scan is a support routine for [fmt.Scanner]; it sets z to the value of
// the scanned number. It accepts formats whose verbs are supported by
// [fmt.Scan] for floating point values, which are:
// 'b' (binary), 'e', 'E', 'f', 'F', 'g' and 'G'.
// Scan doesn't handle ±Inf.
//
func (z *Float) Scan(s fmt.ScanState, ch rune) error {
	return (*big.Float)(z).Scan(s, ch)
}

// Set sets z to the (possibly rounded) value of x and returns z.
// If z's precision is 0, it is changed to the precision of x
// before setting z (and rounding will have no effect).
// Rounding is performed according to z's precision and rounding
// mode; and z's accuracy reports the result error relative to the
// exact (not rounded) result.
//
func (z *Float) Set(x *Float) *Float {
	return (*Float)((*big.Float)(z).Set((*big.Float)(x)))
}

// SetFloat64 sets z to the (possibly rounded) value of x and returns z.
// If z's precision is 0, it is changed to 53 (and rounding will have
// no effect). SetFloat64 panics with [ErrNaN] if x is a NaN.
//
func (z *Float) SetFloat64(x float64) *Float {
	return (*Float)((*big.Float)(z).SetFloat64(x))
}

// SetInf sets z to the infinite Float -Inf if signbit is
// set, or +Inf if signbit is not set, and returns z. The
// precision of z is unchanged and the result is always
// [Exact].
//
func (z *Float) SetInf(signbit bool) *Float {
	return (*Float)((*big.Float)(z).SetInf(signbit))
}

// SetInt sets z to the (possibly rounded) value of x and returns z.
// If z's precision is 0, it is changed to the larger of x.BitLen()
// or 64 (and rounding will have no effect).
//
func (z *Float) SetInt(x *big.Int) *Float {
	return (*Float)((*big.Float)(z).SetInt(x))
}

// SetInt64 sets z to the (possibly rounded) value of x and returns z.
// If z's precision is 0, it is changed to 64 (and rounding will have
// no effect).
//
func (z *Float) SetInt64(x int64) *Float {
	return (*Float)((*big.Float)(z).SetInt64(x))
}

// SetMantExp sets z to mant × 2**exp and returns z.
// The result z has the same precision and rounding mode
// as mant. SetMantExp is an inverse of [Float.MantExp] but does
// not require 0.5 <= |mant| < 1.0. Specifically, for a
// given x of type *[Float], SetMantExp relates to [Float.MantExp]
// as follows:
//
// 	mant := new(Float)
// 	new(Float).SetMantExp(mant, x.MantExp(mant)).Cmp(x) == 0
//
// Special cases are:
//
// 	z.SetMantExp(  ±0, exp) =   ±0
// 	z.SetMantExp(±Inf, exp) = ±Inf
//
// z and mant may be the same in which case z's exponent
// is set to exp.
//
func (z *Float) SetMantExp(mant *Float, exp int) *Float {
	return (*Float)((*big.Float)(z).SetMantExp((*big.Float)(mant), exp))
}

// SetMode sets z's rounding mode to mode and returns an exact z.
// z remains unchanged otherwise.
// z.SetMode(z.Mode()) is a cheap way to set z's accuracy to [Exact].
//
func (z *Float) SetMode(mode RoundingMode) *Float {
	return (*Float)((*big.Float)(z).SetMode(mode))
}

// SetPrec sets z's precision to prec and returns the (possibly) rounded
// value of z. Rounding occurs according to z's rounding mode if the mantissa
// cannot be represented in prec bits without loss of precision.
// SetPrec(0) maps all finite values to ±0; infinite values remain unchanged.
// If prec > [MaxPrec], it is set to [MaxPrec].
//
func (z *Float) SetPrec(prec uint) *Float {
	return (*Float)((*big.Float)(z).SetPrec(prec))
}

// SetRat sets z to the (possibly rounded) value of x and returns z.
// If z's precision is 0, it is changed to the largest of a.BitLen(),
// b.BitLen(), or 64; with x = a/b.
//
func (z *Float) SetRat(x *big.Rat) *Float {
	return (*Float)((*big.Float)(z).SetRat(x))
}

// SetString sets z to the value of s and returns z and a boolean indicating
// success. s must be a floating-point number of the same format as accepted
// by [Float.Parse], with base argument 0. The entire string (not just a prefix) must
// be valid for success. If the operation failed, the value of z is undefined
// but the returned value is nil.
//
func (z *Float) SetString(s string) (*Float, bool) {
	v0, v1 := (*big.Float)(z).SetString(s)
	return (*Float)(v0), v1
}

// SetUint64 sets z to the (possibly rounded) value of x and returns z.
// If z's precision is 0, it is changed to 64 (and rounding will have
// no effect).
//
func (z *Float) SetUint64(x uint64) *Float {
	return (*Float)((*big.Float)(z).SetUint64(x))
}

// Sign returns:
//   - -1 if x < 0;
//   - 0 if x is ±0;
//   - +1 if x > 0.
//
func (x *Float) Sign() int {
	return (*big.Float)(x).Sign()
}

// Signbit reports whether x is negative or negative zero.
//
func (x *Float) Signbit() bool {
	return (*big.Float)(x).Signbit()
}

// Sqrt sets z to the rounded square root of x, and returns it.
//
// If z's precision is 0, it is changed to x's precision before the
// operation. Rounding is performed according to z's precision and
// rounding mode, but z's accuracy is not computed. Specifically, the
// result of z.Acc() is undefined.
//
// The function panics if z < 0. The value of z is undefined in that
// case.
//
func (z *Float) Sqrt(x *Float) *Float {
	return (*Float)((*big.Float)(z).Sqrt((*big.Float)(x)))
}

// Sub sets z to the rounded difference x-y and returns z.
// Precision, rounding, and accuracy reporting are as for [Float.Add].
// Sub panics with [ErrNaN] if x and y are infinities with equal
// signs. The value of z is undefined in that case.
//
func (z *Float) Sub(x *Float, y *Float) *Float {
	return (*Float)((*big.Float)(z).Sub((*big.Float)(x), (*big.Float)(y)))
}

// Uint64 returns the unsigned integer resulting from truncating x
// towards zero. If 0 <= x <= [math.MaxUint64], the result is [Exact]
// if x is an integer and [Below] otherwise.
// The result is (0, [Above]) for x < 0, and ([math.MaxUint64], [Below])
// for x > [math.MaxUint64].
//
func (x *Float) Uint64() (uint64, Accuracy) {
	v0, v1 := (*big.Float)(x).Uint64()
	return v0, v1
}

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
// The result is rounded per the precision and rounding mode of z.
// If z's precision is 0, it is changed to 64 before rounding takes
// effect.
//
func (z *Float) UnmarshalText(text []byte) error {
	return (*big.Float)(z).UnmarshalText(text)
}

// NewFloat allocates and returns a new [Float] set to x,
// with precision 53 and rounding mode [ToNearestEven].
// NewFloat panics with [ErrNaN] if x is a NaN.
//
func NewFloat(x float64) *Float {
	if math.IsNaN(x) {
		panic(ErrNaN("NewFloat(NaN)"))
	}
	return (*Float)(new(big.Float).SetFloat64(x))
}
