// SPDX-License-Identifier: MIT

package bigmath

import (
	"math/big"
	"strconv"
)

// Append appends to buf the string form of the floating-point number x,
// as generated by x.Text, and returns the extended buffer.
//
// For formats 'e', 'E', 'f', 'g', and 'G', this implementation uses
// a fast path that avoids the O(exp × prec²) cost of the standard
// big.Float decimal conversion for numbers with very large exponents.
// For formats 'b', 'p', and 'x', it delegates to math/big (already fast).
func (x *Float) Append(buf []byte, fmt byte, prec int) []byte {
	// delegate to big.Float for the easy formats
	switch fmt {
	case 'b', 'p', 'x':
		return (*big.Float)(x).Append(buf, fmt, prec)
	}

	// sign
	if x.Signbit() {
		buf = append(buf, '-')
	}

	// Inf
	if x.IsInf() {
		if !x.Signbit() {
			buf = append(buf, '+')
		}
		return append(buf, "Inf"...)
	}

	// Algorithm:
	//   1) convert Float to multiprecision decimal
	//   2) round to desired precision
	//   3) read digits out and format

	// 1) convert Float to multiprecision decimal
	var d decimal // == 0.0
	if x.Sign() != 0 && !x.IsInf() {
		// x != 0
		d.init(x)
	}

	// 2) round to desired precision
	shortest := false
	if prec < 0 {
		shortest = true
		roundShortest(&d, x)
		// Precision for shortest representation mode.
		switch fmt {
		case 'e', 'E':
			prec = len(d.mant) - 1
		case 'f':
			prec = max(len(d.mant)-d.exp, 0)
		case 'g', 'G':
			prec = len(d.mant)
		case 'n', 'N':
			shift := ((d.exp-1)%3 + 3) % 3
			sigDigits := shift + 1
			prec = max(0, len(d.mant)-sigDigits)
		}
	} else {
		// round appropriately
		switch fmt {
		case 'e', 'E':
			// one digit before and number of digits after decimal point
			d.round(1 + prec)
		case 'f':
			// number of digits before and after decimal point
			d.round(d.exp + prec)
		case 'g', 'G':
			if prec == 0 {
				prec = 1
			}
			d.round(prec)
		case 'n', 'N':
			// engineering may need up to 3 leading digits
			d.round(3 + prec)
		}
	}

	// 3) read digits out and format
	switch fmt {
	case 'e', 'E':
		return fmtE(buf, fmt, prec, d)
	case 'n', 'N':
		return fmtN(buf, fmt, prec, d)
	case 'f':
		return fmtF(buf, prec, d)
	case 'g', 'G':
		// trim trailing fractional zeros in %e format
		eprec := prec
		if eprec > len(d.mant) && len(d.mant) >= d.exp {
			eprec = len(d.mant)
		}
		// %e is used if the exponent from the conversion
		// is less than -4 or greater than or equal to the precision.
		// If precision was the shortest possible, use eprec = 6 for
		// this decision.
		if shortest {
			eprec = 6
		}
		exp := d.exp - 1
		if exp < -4 || exp >= eprec {
			if prec > len(d.mant) {
				prec = len(d.mant)
			}
			return fmtE(buf, fmt+'e'-'g', prec-1, d)
		}
		if prec > d.exp {
			prec = len(d.mant)
		}
		return fmtF(buf, max(prec-d.exp, 0), d)
	}

	// unknown format
	if x.Signbit() {
		buf = buf[:len(buf)-1] // sign was added prematurely - remove it again
	}
	return append(buf, '%', fmt)
}

func roundShortest(d *decimal, x *Float) {
	// if the mantissa is zero, the number is zero - stop now
	if len(d.mant) == 0 {
		return
	}

	// Approach: All numbers in the interval [x - 1/2ulp, x + 1/2ulp]
	// (possibly exclusive) round to x for the given precision of x.
	// Compute the lower and upper bound in decimal form and find the
	// shortest decimal number d such that lower <= d <= upper.

	// 1) Compute normalized mantissa mant and exponent exp for x such
	// that the lsb of mant corresponds to 1/2 ulp for the precision of
	// x (i.e., for mant we want x.prec + 1 bits).
	var lower, upper decimal
	exp := x.MantExp(nil)
	prec := x.Prec()
	// x = mant * 2**exp with lsb(mant) == 1/2 ulp of x.prec

	// ½ ulp = 2^(exp - prec)
	halfULP := new(Float).SetMantExp(one, exp-int(prec))
	t := newFloat(prec + 1)
	// Lower bound: x - ½ulp
	lower.init(t.Sub(x, halfULP))
	// Upper bound: x + ½ulp
	upper.init(t.Add(x, halfULP))
	// We should be working with the absolute value, swap upper lower for x<0
	if x.Signbit() {
		lower, upper = upper, lower
	}

	// The upper and lower bounds are possible outputs only if
	// the original mantissa is even, so that ToNearestEven rounding
	// would round to the original mantissa and not the neighbors.
	inclusive := !x.isOdd()

	// Now we can figure out the minimum number of digits required.
	// Walk along until d has distinguished itself from upper and lower.
	for i, m := range d.mant {
		l := lower.at(i)
		u := upper.at(i)

		// Okay to round down (truncate) if lower has a different digit
		// or if lower is inclusive and is exactly the result of rounding
		// down (i.e., and we have reached the final digit of lower).
		okdown := l != m || inclusive && i+1 == len(lower.mant)

		// Okay to round up if upper has a different digit and either upper
		// is inclusive or upper is bigger than the result of rounding up.
		okup := m != u && (inclusive || m+1 < u || i+1 < len(upper.mant))

		// If it's okay to do either, then round to the nearest one.
		// If it's okay to do only one, do it.
		switch {
		case okdown && okup:
			d.round(i + 1)
			return
		case okdown:
			d.roundDown(i + 1)
			return
		case okup:
			d.roundUp(i + 1)
			return
		}
	}
}

// %e: d.ddddde±dd
func fmtE(buf []byte, fmt byte, prec int, d decimal) []byte {
	// first digit
	ch := byte('0')
	if len(d.mant) > 0 {
		ch = d.mant[0]
	}
	buf = append(buf, ch)

	// .moredigits
	if prec > 0 {
		buf = append(buf, '.')
		i := 1
		m := min(len(d.mant), prec+1)
		if i < m {
			buf = append(buf, d.mant[i:m]...)
			i = m
		}
		for ; i <= prec; i++ {
			buf = append(buf, '0')
		}
	}

	// e±
	buf = append(buf, fmt)
	var exp int64
	if len(d.mant) > 0 {
		exp = int64(d.exp) - 1 // -1 because first digit was printed before '.'
	}
	if exp < 0 {
		ch = '-'
		exp = -exp
	} else {
		ch = '+'
	}
	buf = append(buf, ch)

	// dd...d
	if exp < 10 {
		buf = append(buf, '0') // at least 2 exponent digits
	}
	return strconv.AppendInt(buf, exp, 10)
}

// %f: ddddddd.ddddd
func fmtF(buf []byte, prec int, d decimal) []byte {
	// integer, padded with zeros as needed
	if d.exp > 0 {
		m := min(len(d.mant), d.exp)
		buf = append(buf, d.mant[:m]...)
		for ; m < d.exp; m++ {
			buf = append(buf, '0')
		}
	} else {
		buf = append(buf, '0')
	}

	// fraction
	if prec > 0 {
		buf = append(buf, '.')
		for i := range prec {
			buf = append(buf, d.at(d.exp+i))
		}
	}

	return buf
}

// %n, %N: engineering notation — exponent is always a multiple of 3,
// mantissa has 1-3 digits before the decimal point.
// fmtN formats d in engineering notation: exponent is always a multiple of 3,
// mantissa has 1-3 digits before the decimal point.
// fmt is 'n' (lowercase 'e' separator) or 'N' (uppercase 'E' separator).
func fmtN(buf []byte, fmt byte, prec int, d decimal) []byte {
	// map fmt to exponent separator
	var sep byte
	if fmt == 'N' {
		sep = 'E'
	} else {
		sep = 'e'
	}

	// special case 0
	if len(d.mant) == 0 {
		buf = append(buf, '0')
		if prec > 0 {
			buf = append(buf, '.')
			for range prec {
				buf = append(buf, '0')
			}
		}
		buf = append(buf, sep)
		buf = append(buf, "+00"...)
		return buf
	}

	// raw scientific exponent
	rawExp := int64(d.exp) - 1
	// shift = rawExp % 3 (mathematical modulo: always in [0, 2])
	shift := int(rawExp % 3)
	if shift < 0 {
		shift += 3
	}
	engExp := rawExp - int64(shift)
	sigDigits := shift + 1 // 1, 2, or 3 leading digits

	// leading digits (may need zero-padding if mant is shorter)
	n := min(sigDigits, len(d.mant))
	buf = append(buf, d.mant[:n]...)
	for i := n; i < sigDigits; i++ {
		buf = append(buf, '0')
	}

	// fractional digits
	if prec > 0 {
		buf = append(buf, '.')
		i := sigDigits
		m := min(len(d.mant), sigDigits+prec)
		if i < m {
			buf = append(buf, d.mant[i:m]...)
			i = m
		}
		for ; i < sigDigits+prec; i++ {
			buf = append(buf, '0')
		}
	}

	// exponent separator (±ee)
	buf = append(buf, sep)
	if engExp < 0 {
		buf = append(buf, '-')
		engExp = -engExp
	} else {
		buf = append(buf, '+')
	}

	// at least 2 exponent digits
	if engExp < 10 {
		buf = append(buf, '0')
	}
	return strconv.AppendInt(buf, engExp, 10)
}
