#!/usr/bin/env python3

# SPDX-License-Identifier: MIT

import sys
import argparse
import gmpy2
import builtins

def generate_go_tests(input_file, output_file, precision):
    
    ctx = gmpy2.get_context()
    ctx.precision = precision
    # Attempt to match Go's math/big exponent limits as closely as MPFR allows
    # Go: -2^31 to 2^31-1. MPFR is often limited to 2^30-1 or 2^62-1.
    GO_EMAX = 2147483647
    GO_EMIN = -2147483648
    ctx.emax = min(GO_EMAX, gmpy2.get_emax_max())
    ctx.emin = max(GO_EMIN, gmpy2.get_emin_min())

    header = f"""// Code generated by {sys.argv[0]}; DO NOT EDIT.

package bigmath_test

const dataPrec = {precision}

type testData struct {{
	fn   string
	args []string
	res  string
}}

var data = []testData{{
"""
    footer = "}\n"

    # Open the output stream
    out = open(output_file, 'w') if output_file else sys.stdout
    
    try:
        # Write the header immediately
        out.write(header)
        
        # Process the input file
        with open(input_file, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                
                parts = line.split()
                func_name = parts[0]
                str_args = parts[1:]
                
                # Logic that might panic
                mpfr_args = [gmpy2.mpfr(arg) for arg in str_args]
                
                # Lookup function: gmpy2 -> globals -> builtins
                func = getattr(gmpy2, func_name, None)
                if func is None:
                    func = globals().get(func_name)
                if func is None:
                    func = getattr(builtins, func_name, None)
                
                if func is None:
                    raise AttributeError(f"function '{func_name}' not found")
                
                result = func(*mpfr_args)
                
                # Hex float format for bit-perfect transfer
                res_str = format(result, 'a')
                go_args = ", ".join(f'"{a}"' for a in str_args)
                
                out.write(f'\t{{"{func_name}", []string{{{go_args}}}, "{res_str}"}},\n')
                
    finally:
        # Ensure the Go file is syntactically closed even if a panic occurs
        out.write(footer)
        if output_file:
            out.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Go test data.")
    parser.add_argument("input", help="Input text file")
    parser.add_argument("-o", "--output", help="Output Go file")
    parser.add_argument("-p", "--precision", type=int, default=256, 
                        help="Precision in bits (default: 256)")

    args = parser.parse_args()
    generate_go_tests(args.input, args.output, args.precision)
